CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL
);

ALTER TABLE tasks
ADD COLUMN user_id INTEGER REFERENCES users(id) ON DELETE CASCADE;